all:
	g++ --std=c++14 -Wall -O3 client.cpp -o client -lboost_system -lboost_thread -lpthread
	g++ --std=c++14 -Wall -O3 server.cpp -o server -lboost_system -lboost_thread -lpthread
clean:
	rm client server
